In [254]:
import pandas as pd
pf = pd.read_csv('../data/presidents.csv', index_col='id')
pf['col_adjusted_base_comp'] = pf["base_comp"]/pf["cost_of_living"]

In [255]:
pf.head()

,name,photo,org_name,state,cost_of_living,start_term,base_comp,revenues_2014,days_employed_2014,tuition_fees_201415,enrollment,col_adjusted_base_comp
id,,,,,,,,,,,,
0,Joseph A. Alutto,204796_14571.jpg,Ohio State University,Ohio,0.896,201307,634572,2854674173,184,10037,58322,708227.678571
1,Elson S. Floyd,floyd_3875.jpg,Washington State University,Washington,1.032,200705,725000,921662039,2437,12428,28686,702519.379845
2,Paula Allen-Meares,allen-meares_1158.jpg,University of Illinois at Chicago,Illinois,1.010,200901,422458,1877887288,1826,13634,27969,418275.247525
3,Renu Khator,khator_3639.jpg,University of Houston,Texas,0.967,200801,700000,948745952,2192,8605,40914,723888.314374
4,Robert L. Barchi,barchi_22204.jpg,Rutgers University at New Brunswick,New Jersey,1.145,201209,649624,2284387000,487,13813,48378,567357.205240

In [256]:
len(pf)

142

In [257]:
pf[["base_comp"]].mean()

base_comp    421687.485915
dtype: float64

In [258]:
pf[["base_comp"]].median()

base_comp    410146.5
dtype: float64

In [259]:
from sklearn.neighbors import NearestNeighbors
from sklearn import preprocessing
import numpy as np
initial = np.genfromtxt('../data/presidents.csv', dtype=float, delimiter=',', skip_header=1, usecols=range(7, 10))
initial[:5]

array([[  6.34572000e+05,   2.85467417e+09,   1.84000000e+02],
       [  7.25000000e+05,   9.21662039e+08,   2.43700000e+03],
       [  4.22458000e+05,   1.87788729e+09,   1.82600000e+03],
       [  7.00000000e+05,   9.48745952e+08,   2.19200000e+03],
       [  6.49624000e+05,   2.28438700e+09,   4.87000000e+02]])

In [260]:
presidents = preprocessing.normalize(initial)
presidents[:5]

array([[  2.22292264e-04,   9.99999975e-01,   6.44556907e-08],
       [  7.86622151e-04,   9.99999691e-01,   2.64413542e-06],
       [  2.24964508e-04,   9.99999975e-01,   9.72369303e-07],
       [  7.37815859e-04,   9.99999728e-01,   2.31041766e-06],
       [  2.84375622e-04,   9.99999960e-01,   2.13186286e-07]])

In [261]:
nbrs = NearestNeighbors(n_neighbors=8, algorithm='ball_tree').fit(presidents)
distances, indices = nbrs.kneighbors(presidents)
distances[:5], indices[:5]

(array([[  0.00000000e+00,   1.88630019e-06,   2.25039825e-06,
           2.82226772e-06,   5.28304739e-06,   7.06326053e-06,
           9.64841586e-06,   1.38840652e-05],
        [  0.00000000e+00,   5.47867487e-06,   8.68424075e-06,
           1.72150950e-05,   2.46371996e-05,   2.72161669e-05,
           2.81428597e-05,   2.84105110e-05],
        [  0.00000000e+00,   1.02075723e-06,   2.75890378e-06,
           2.82226772e-06,   4.23575311e-06,   4.27662870e-06,
           1.12373219e-05,   1.23346207e-05],
        [  0.00000000e+00,   5.29103440e-06,   1.42573066e-05,
           1.47215799e-05,   1.83980011e-05,   1.90233746e-05,
           3.18335335e-05,   3.48110350e-05],
        [  0.00000000e+00,   3.30454030e-06,   5.05860041e-06,
           5.17383033e-06,   1.76852413e-05,   3.96943509e-05,
           3.97435111e-05,   4.30381730e-05]]),
 array([[  0,  36,  86,   2,  39,  28,  19,  55],
        [  1, 134,  32,  93,  14, 140, 106,  82],
        [  2,  36,  39,   0,  86,  28,  55,  19],
        [  3,  47, 111,  33,  61,  89,  93,  74],
        [  4, 114,  56,  71, 100,  46,  67,  12]]))

In [262]:
pf["neighbors"] = indices.tolist()

pf.loc[indices[:1][0].tolist()]

,name,photo,org_name,state,cost_of_living,start_term,base_comp,revenues_2014,days_employed_2014,tuition_fees_201415,enrollment,col_adjusted_base_comp,neighbors
id,,,,,,,,,,,,,
0,Joseph A. Alutto,204796_14571.jpg,Ohio State University,Ohio,0.896,201307,634572,2854674173,184,10037,58322,708227.678571,"[0, 36, 86, 2, 39, 28, 19, 55]"
36,Phyllis M. Wise,wise_3869.jpg,University of Illinois at Urbana-Champaign,Illinois,1.010,201110,530501,2366647420,823,15020,45140,525248.514851,"[36, 2, 0, 39, 86, 28, 19, 55]"
86,Michael V. Drake,drake_546.jpg,University of California at Irvine,California,1.123,200507,392000,1775357000,3106,13179,30051,349065.004452,"[86, 0, 36, 2, 39, 19, 28, 55]"
2,Paula Allen-Meares,allen-meares_1158.jpg,University of Illinois at Chicago,Illinois,1.010,200901,422458,1877887288,1826,13634,27969,418275.247525,"[2, 36, 39, 0, 86, 28, 55, 19]"
39,Carol L. Folt,199120_10926.jpg,University of North Carolina at Chapel Hill,North Carolina,0.917,201307,520000,2284958065,184,8336,29135,567066.521265,"[39, 28, 2, 36, 0, 86, 55, 12]"
28,J. Bernard Machen,machen_843.jpg,University of Florida,Florida,0.988,200312,564553,2463049000,3684,6313,49459,571409.919028,"[28, 39, 2, 36, 0, 55, 86, 12]"
19,Eric W. Kaler,kaler_1910.jpg,University of Minnesota-Twin Cities,Minnesota,0.976,201107,610000,2868600997,915,13560,51147,625000.000000,"[19, 43, 86, 0, 36, 2, 39, 28]"
55,Mitchell E. Daniels Jr.,daniels_22202.jpg,Purdue University at West Lafayette,Indiana,0.914,201301,420000,1778337652,365,10002,39752,459518.599562,"[55, 12, 28, 67, 46, 39, 2, 36]"

In [263]:
def neighbor_averages(ns, factor):
    return pf.loc[ns][[factor]].mean()[0]

pf['col_adjusted_neighbor_average'] =  pf["neighbors"].map(lambda x: neighbor_averages(ns=x, factor='col_adjusted_base_comp'))
pf['neighbor_average'] = pf["neighbors"].map(lambda x: neighbor_averages(x, factor='base_comp'))
pf.head()

,name,photo,org_name,state,cost_of_living,start_term,base_comp,revenues_2014,days_employed_2014,tuition_fees_201415,enrollment,col_adjusted_base_comp,neighbors,col_adjusted_neighbor_average,neighbor_average
id,,,,,,,,,,,,,,,
0,Joseph A. Alutto,204796_14571.jpg,Ohio State University,Ohio,0.896,201307,634572,2854674173,184,10037,58322,708227.678571,"[0, 36, 86, 2, 39, 28, 19, 55]",527976.435657,511760.500
1,Elson S. Floyd,floyd_3875.jpg,Washington State University,Washington,1.032,200705,725000,921662039,2437,12428,28686,702519.379845,"[1, 134, 32, 93, 14, 140, 106, 82]",415544.291226,402006.125
2,Paula Allen-Meares,allen-meares_1158.jpg,University of Illinois at Chicago,Illinois,1.010,200901,422458,1877887288,1826,13634,27969,418275.247525,"[2, 36, 39, 0, 86, 28, 55, 19]",527976.435657,511760.500
3,Renu Khator,khator_3639.jpg,University of Houston,Texas,0.967,200801,700000,948745952,2192,8605,40914,723888.314374,"[3, 47, 111, 33, 61, 89, 93, 74]",466293.630910,444687.750
4,Robert L. Barchi,barchi_22204.jpg,Rutgers University at New Brunswick,New Jersey,1.145,201209,649624,2284387000,487,13813,48378,567357.205240,"[4, 114, 56, 71, 100, 46, 67, 12]",459530.880914,452670.875

In [264]:
import json
pf.to_json(orient='records')

'[{"name":"Joseph A. Alutto","photo":"204796_14571.jpg","org_name":"Ohio State University","state":"Ohio","cost_of_living":0.896,"start_term":201307,"base_comp":634572,"revenues_2014":2854674173,"days_employed_2014":184,"tuition_fees_201415":10037,"enrollment":58322,"col_adjusted_base_comp":708227.6785714286,"neighbors":[0,36,86,2,39,28,19,55],"col_adjusted_neighbor_average":527976.4356569655,"neighbor_average":511760.5},{"name":"Elson S. Floyd","photo":"floyd_3875.jpg","org_name":"Washington State University","state":"Washington","cost_of_living":1.032,"start_term":200705,"base_comp":725000,"revenues_2014":921662039,"days_employed_2014":2437,"tuition_fees_201415":12428,"enrollment":28686,"col_adjusted_base_comp":702519.3798449612,"neighbors":[1,134,32,93,14,140,106,82],"col_adjusted_neighbor_average":415544.291226324,"neighbor_average":402006.125},{"name":"Paula Allen-Meares","photo":"allen-meares_1158.jpg","org_name":"University of Illinois at Chicago","state":"Illinois","cost_of_living":1.01,"start_term":200901,"base_comp":422458,"revenues_2014":1877887288,"days_employed_2014":1826,"tuition_fees_201415":13634,"enrollment":27969,"col_adjusted_base_comp":418275.2475247525,"neighbors":[2,36,39,0,86,28,55,19],"col_adjusted_neighbor_average":527976.4356569655,"neighbor_average":511760.5},{"name":"Renu Khator","photo":"khator_3639.jpg","org_name":"University of Houston","state":"Texas","cost_of_living":0.967,"start_term":200801,"base_comp":700000,"revenues_2014":948745952,"days_employed_2014":2192,"tuition_fees_201415":8605,"enrollment":40914,"col_adjusted_base_comp":723888.3143743536,"neighbors":[3,47,111,33,61,89,93,74],"col_adjusted_neighbor_average":466293.6309099868,"neighbor_average":444687.75},{"name":"Robert L. Barchi","photo":"barchi_22204.jpg","org_name":"Rutgers University at New Brunswick","state":"New Jersey","cost_of_living":1.145,"start_term":201209,"base_comp":649624,"revenues_2014":2284387000,"days_employed_2014":487,"tuition_fees_201415":13813,"enrollment":48378,"col_adjusted_base_comp":567357.2052401747,"neighbors":[4,114,56,71,100,46,67,12],"col_adjusted_neighbor_average":459530.8809139314,"neighbor_average":452670.875},{"name":"Judy L. Genshaft","photo":"genshaft_845.jpg","org_name":"University of South Florida","state":"Florida","cost_of_living":0.988,"start_term":200007,"base_comp":470000,"revenues_2014":1038090336,"days_employed_2014":4932,"tuition_fees_201415":6410,"enrollment":41938,"col_adjusted_base_comp":475708.5020242915,"neighbors":[5,65,9,59,20,48,38,72],"col_adjusted_neighbor_average":507290.1408507449,"neighbor_average":478404.625},{"name":"Mary Sue Coleman","photo":"coleman_14784.jpg","org_name":"University of Michigan at Ann Arbor","state":"Michigan","cost_of_living":0.942,"start_term":200208,"base_comp":603357,"revenues_2014":4500602000,"days_employed_2014":4171,"tuition_fees_201415":13486,"enrollment":43625,"col_adjusted_base_comp":640506.3694267515,"neighbors":[6,76,77,83,17,51,43,19],"col_adjusted_neighbor_average":491569.0298161532,"neighbor_average":506149.875},{"name":"Eli Capilouto","photo":"capilouto_1430.jpg","org_name":"University of Kentucky","state":"Kentucky","cost_of_living":0.891,"start_term":201107,"base_comp":535500,"revenues_2014":1497398855,"days_employed_2014":915,"tuition_fees_201415":10616,"enrollment":29203,"col_adjusted_base_comp":601010.101010101,"neighbors":[7,41,37,126,26,79,66,97],"col_adjusted_neighbor_average":456069.6084894814,"neighbor_average":454162.25},{"name":"Judy Bonner","photo":"bonner_63.jpg","org_name":"University of Alabama at Tuscaloosa","state":"Alabama","cost_of_living":0.877,"start_term":201211,"base_comp":565000,"revenues_2014":876199740,"days_employed_2014":426,"tuition_fees_201415":9826,"enrollment":36047,"col_adjusted_base_comp":644241.7331812999,"neighbors":[8,99,34,45,121,25,21,57],"col_adjusted_neighbor_average":506922.5202504318,"neighbor_average":482112.875},{"name":"Michael A. McRobbie","photo":"mcrobbie_1201.jpg","org_name":"Indiana University at Bloomington","state":"Indiana","cost_of_living":0.914,"start_term":200707,"base_comp":555745,"revenues_2014":1263487296,"days_employed_2014":2376,"tuition_fees_201415":10388,"enrollment":46416,"col_adjusted_base_comp":608036.1050328227,"neighbors":[9,65,5,38,72,59,20,30],"col_adjusted_neighbor_average":503259.2897187823,"neighbor_average":472767.125},{"name":"Samuel L. Stanley Jr.","photo":"stanley_2547.jpg","org_name":"Stony Brook University","state":"New York","cost_of_living":1.153,"start_term":200907,"base_comp":650000,"revenues_2014":950415222,"days_employed_2014":1645,"tuition_fees_201415":8430,"enrollment":24607,"col_adjusted_base_comp":563746.7476149176,"neighbors":[10,21,11,128,74,121,45,99],"col_adjusted_neighbor_average":466503.8937230614,"neighbor_average":478596.625},{"name":"Satish K. Tripathi","photo":"tripathi_2544.jpg","org_name":"University at Buffalo","state":"New York","cost_of_living":1.153,"start_term":201104,"base_comp":650000,"revenues_2014":936243254,"days_employed_2014":1006,"tuition_fees_201415":8870,"enrollment":29995,"col_adjusted_base_comp":563746.7476149176,"neighbors":[11,128,74,10,21,61,111,121],"col_adjusted_neighbor_average":453200.444479804,"neighbor_average":460472.75},{"name":"Lou Anna K. Simon","photo":"simon_1811.jpg","org_name":"Michigan State University","state":"Michigan","cost_of_living":0.942,"start_term":200501,"base_comp":520000,"revenues_2014":2154480616,"days_employed_2014":3287,"tuition_fees_201415":13200,"enrollment":50081,"col_adjusted_base_comp":552016.9851380042,"neighbors":[12,67,46,55,28,39,2,36],"col_adjusted_neighbor_average":492876.786538027,"neighbor_average":478882.75},{"name":"John C. Hitt","photo":"hitt_842.jpg","org_name":"University of Central Florida","state":"Florida","cost_of_living":0.988,"start_term":199203,"base_comp":491000,"revenues_2014":845429710,"days_employed_2014":7976,"tuition_fees_201415":6368,"enrollment":60767,"col_adjusted_base_comp":496963.5627530364,"neighbors":[13,70,29,75,60,31,58,49],"col_adjusted_neighbor_average":483001.3621839455,"neighbor_average":462257.625},{"name":"Lester A. Lefton","photo":"lefton_2831.jpg","org_name":"Kent State University at Kent (Ohio)","state":"Ohio","cost_of_living":0.896,"start_term":200607,"base_comp":426156,"revenues_2014":525388883,"days_employed_2014":2741,"tuition_fees_201415":10012,"enrollment":29477,"col_adjusted_base_comp":475620.5357142857,"neighbors":[14,140,106,82,54,116,134,18],"col_adjusted_neighbor_average":375413.1564998218,"neighbor_average":371501.0},{"name":"Santa J. Ono","photo":"ono_22226.jpg","org_name":"University of Cincinnati","state":"Ohio","cost_of_living":0.896,"start_term":201210,"base_comp":525000,"revenues_2014":1017133849,"days_employed_2014":457,"tuition_fees_201415":11000,"enrollment":35313,"col_adjusted_base_comp":585937.5000000001,"neighbors":[15,108,103,68,119,129,115,73],"col_adjusted_neighbor_average":398305.399357161,"neighbor_average":382896.0},{"name":"James R. Ramsey","photo":"ramsey_1446.jpg","org_name":"University of Louisville","state":"Kentucky","cost_of_living":0.891,"start_term":200211,"base_comp":624000,"revenues_2014":589741000,"days_employed_2014":4079,"tuition_fees_201415":10432,"enrollment":21561,"col_adjusted_base_comp":700336.7003367004,"neighbors":[16,96,133,130,44,81,40,131],"col_adjusted_neighbor_average":419547.2276536457,"neighbor_average":392060.625},{"name":"Michael K. Young","photo":"young_3682.jpg","org_name":"University of Washington","state":"Washington","cost_of_living":1.032,"start_term":201107,"base_comp":622008,"revenues_2014":3346490090,"days_employed_2014":915,"tuition_fees_201415":12394,"enrollment":44784,"col_adjusted_base_comp":602720.9302325582,"neighbors":[17,83,51,77,43,19,86,0],"col_adjusted_neighbor_average":497362.7776088371,"neighbor_average":507051.75},{"name":"Angel Cabrera","photo":"caberera_22177.jpg","org_name":"George Mason University","state":"Virginia","cost_of_living":1.03,"start_term":201207,"base_comp":536049,"revenues_2014":642906015,"days_employed_2014":549,"tuition_fees_201415":10382,"enrollment":33729,"col_adjusted_base_comp":520435.9223300971,"neighbors":[18,116,23,54,82,106,140,14],"col_adjusted_neighbor_average":393500.1414990652,"neighbor_average":385834.875},{"name":"Eric W. Kaler","photo":"kaler_1910.jpg","org_name":"University of Minnesota-Twin Cities","state":"Minnesota","cost_of_living":0.976,"start_term":201107,"base_comp":610000,"revenues_2014":2868600997,"days_employed_2014":915,"tuition_fees_201415":13560,"enrollment":51147,"col_adjusted_base_comp":625000.0,"neighbors":[19,43,86,0,36,2,39,28],"col_adjusted_neighbor_average":537806.5245975689,"neighbor_average":521754.25},{"name":"Michael M. Crow","photo":"crow_93.jpg","org_name":"Arizona State University","state":"Arizona","cost_of_living":0.971,"start_term":200207,"base_comp":566200,"revenues_2014":1184234350,"days_employed_2014":4202,"tuition_fees_201415":10157,"enrollment":50320,"col_adjusted_base_comp":583110.1956745624,"neighbors":[20,59,48,115,129,5,103,108],"col_adjusted_neighbor_average":438947.3728968166,"neighbor_average":417498.5},{"name":"F. King Alexander","photo":"alexander_22187.jpg","org_name":"Louisiana State University at Baton Rouge","state":"Louisiana","cost_of_living":0.912,"start_term":201306,"base_comp":600000,"revenues_2014":889871947,"days_employed_2014":214,"tuition_fees_201415":8750,"enrollment":31044,"col_adjusted_base_comp":657894.7368421053,"neighbors":[21,10,121,45,99,11,128,74],"col_adjusted_neighbor_average":466503.8937230615,"neighbor_average":478596.625},{"name":"Ronald M. Berkman","photo":"berkman_2798.jpg","org_name":"Cleveland State University","state":"Ohio","cost_of_living":0.896,"start_term":200907,"base_comp":430000,"revenues_2014":311295541,"days_employed_2014":1645,"tuition_fees_201415":9686,"enrollment":16936,"col_adjusted_base_comp":479910.7142857143,"neighbors":[22,136,42,88,64,102,110,123],"col_adjusted_neighbor_average":399384.291976224,"neighbor_average":378928.25},{"name":"David C. Hodge","photo":"hodge_2853.jpg","org_name":"Miami University (Ohio)","state":"Ohio","cost_of_living":0.896,"start_term":200607,"base_comp":409209,"revenues_2014":485092056,"days_employed_2014":2741,"tuition_fees_201415":14287,"enrollment":18620,"col_adjusted_base_comp":456706.4732142857,"neighbors":[23,18,124,116,54,90,82,106],"col_adjusted_neighbor_average":396173.997325252,"neighbor_average":389287.875},{"name":"Joel S. Bloom","photo":"bloom_22193.jpg","org_name":"New Jersey Institute of Technology","state":"New Jersey","cost_of_living":1.145,"start_term":201201,"base_comp":495000,"revenues_2014":400008000,"days_employed_2014":731,"tuition_fees_201415":15648,"enrollment":10646,"col_adjusted_base_comp":432314.4104803493,"neighbors":[24,137,69,138,104,50,95,123],"col_adjusted_neighbor_average":377014.8076484263,"neighbor_average":370641.375},{"name":"Mark B. Rosenberg","photo":"rosenberg_840.jpg","org_name":"Florida International University","state":"Florida","cost_of_living":0.988,"start_term":200908,"base_comp":502578,"revenues_2014":813566360,"days_employed_2014":1614,"tuition_fees_201415":6497,"enrollment":49610,"col_adjusted_base_comp":508682.1862348178,"neighbors":[25,57,52,49,34,60,75,8],"col_adjusted_neighbor_average":529663.4157384562,"neighbor_average":491389.25},{"name":"Susan Herbst","photo":"herbst_697.jpg","org_name":"University of Connecticut","state":"Connecticut","cost_of_living":1.085,"start_term":201105,"base_comp":525000,"revenues_2014":1506774204,"days_employed_2014":976,"tuition_fees_201415":12700,"enrollment":26541,"col_adjusted_base_comp":483870.9677419355,"neighbors":[26,41,7,37,126,66,79,97],"col_adjusted_neighbor_average":456069.6084894814,"neighbor_average":454162.25},{"name":"Robert A. Altenkirch","photo":"altenkirch_22221.jpg","org_name":"University of Alabama at Huntsville","state":"Alabama","cost_of_living":0.877,"start_term":201109,"base_comp":472000,"revenues_2014":208801549,"days_employed_2014":853,"tuition_fees_201415":9158,"enrollment":7348,"col_adjusted_base_comp":538198.4036488028,"neighbors":[27,120,78,107,84,105,135,117],"col_adjusted_neighbor_average":385842.7243760648,"neighbor_average":359322.75},{"name":"J. Bernard Machen","photo":"machen_843.jpg","org_name":"University of Florida","state":"Florida","cost_of_living":0.988,"start_term":200312,"base_comp":564553,"revenues_2014":2463049000,"days_employed_2014":3684,"tuition_fees_201415":6313,"enrollment":49459,"col_adjusted_base_comp":571409.9190283401,"neighbors":[28,39,2,36,0,55,86,12],"col_adjusted_neighbor_average":518853.5587992161,"neighbor_average":500510.5},{"name":"Michael Rao","photo":"rao_3777.jpg","org_name":"Virginia Commonwealth University","state":"Virginia","cost_of_living":1.03,"start_term":200907,"base_comp":503155,"revenues_2014":865200606,"days_employed_2014":1645,"tuition_fees_201415":12398,"enrollment":30848,"col_adjusted_base_comp":488500.0,"neighbors":[29,13,70,75,60,31,58,49],"col_adjusted_neighbor_average":483001.3621839455,"neighbor_average":462257.625},{"name":"Ray Watts","photo":"watts_22220.jpg","org_name":"University of Alabama at Birmingham","state":"Alabama","cost_of_living":0.877,"start_term":201302,"base_comp":447550,"revenues_2014":1120886254,"days_employed_2014":334,"tuition_fees_201415":7510,"enrollment":18698,"col_adjusted_base_comp":510319.2702394527,"neighbors":[30,38,62,72,97,79,37,9],"col_adjusted_neighbor_average":474705.7409746678,"neighbor_average":453458.625},{"name":"Michael R. Gottfredson","photo":"gottfredson_22230.jpg","org_name":"University of Oregon","state":"Oregon","cost_of_living":0.987,"start_term":201208,"base_comp":444004,"revenues_2014":779478595,"days_employed_2014":518,"tuition_fees_201415":9918,"enrollment":24096,"col_adjusted_base_comp":449852.0770010132,"neighbors":[31,58,29,13,122,70,75,60],"col_adjusted_neighbor_average":457423.0798282395,"neighbor_average":441584.25},{"name":"LLoyd A. Jacobs","photo":"jacobs_2921.jpg","org_name":"University of Toledo","state":"Ohio","cost_of_living":0.896,"start_term":200311,"base_comp":392700,"revenues_2014":503889806,"days_employed_2014":3714,"tuition_fees_201415":9463,"enrollment":20626,"col_adjusted_base_comp":438281.2500000001,"neighbors":[32,1,93,134,89,33,14,140],"col_adjusted_neighbor_average":439897.7915305566,"neighbor_average":421149.125},{"name":"David E. Daniel","photo":"daniel_3652.jpg","org_name":"University of Texas at Dallas","state":"Texas","cost_of_living":0.967,"start_term":200506,"base_comp":518279,"revenues_2014":688865593,"days_employed_2014":3136,"tuition_fees_201415":10864,"enrollment":23095,"col_adjusted_base_comp":535965.873836608,"neighbors":[33,89,3,93,47,32,111,61],"col_adjusted_neighbor_average":459298.8332429362,"neighbor_average":440150.25},{"name":"Harris Pastides","photo":"pastides_3344.jpg","org_name":"University of South Carolina at Columbia","state":"South Carolina","cost_of_living":0.905,"start_term":200808,"base_comp":531200,"revenues_2014":838487410,"days_employed_2014":1979,"tuition_fees_201415":11158,"enrollment":32971,"col_adjusted_base_comp":586961.3259668509,"neighbors":[34,8,25,99,45,57,121,52],"col_adjusted_neighbor_average":486120.3286010957,"neighbor_average":467748.875},{"name":"Mark P. Becker","photo":"becker_913.jpg","org_name":"Georgia State University","state":"Georgia","cost_of_living":0.919,"start_term":200901,"base_comp":530600,"revenues_2014":591247060,"days_employed_2014":1826,"tuition_fees_201415":8618,"enrollment":32556,"col_adjusted_base_comp":577366.702937976,"neighbors":[35,113,53,63,118,80,90,98],"col_adjusted_neighbor_average":422138.9720343338,"neighbor_average":396783.5},{"name":"Phyllis M. Wise","photo":"wise_3869.jpg","org_name":"University of Illinois at Urbana-Champaign","state":"Illinois","cost_of_living":1.01,"start_term":201110,"base_comp":530501,"revenues_2014":2366647420,"days_employed_2014":823,"tuition_fees_201415":15020,"enrollment":45140,"col_adjusted_base_comp":525248.5148514851,"neighbors":[36,2,0,39,86,28,19,55],"col_adjusted_neighbor_average":527976.4356569655,"neighbor_average":511760.5},{"name":"Wallace D. Loh","photo":"loh_1612.jpg","org_name":"University of Maryland at College Park","state":"Maryland","cost_of_living":1.109,"start_term":201011,"base_comp":526590,"revenues_2014":1464916824,"days_employed_2014":1157,"tuition_fees_201415":9427,"enrollment":37610,"col_adjusted_base_comp":474833.1830477908,"neighbors":[37,7,41,126,26,79,97,62],"col_adjusted_neighbor_average":457429.7825917664,"neighbor_average":455412.25},{"name":"W. Randolph Woodson","photo":"woodson_2731.jpg","org_name":"North Carolina State University","state":"North Carolina","cost_of_living":0.917,"start_term":201004,"base_comp":520000,"revenues_2014":1250491664,"days_employed_2014":1371,"tuition_fees_201415":8296,"enrollment":33989,"col_adjusted_base_comp":567066.5212649945,"neighbors":[38,72,30,9,65,62,97,5],"col_adjusted_neighbor_average":472429.3829483513,"neighbor_average":446360.625},{"name":"Carol L. Folt","photo":"199120_10926.jpg","org_name":"University of North Carolina at Chapel Hill","state":"North Carolina","cost_of_living":0.917,"start_term":201307,"base_comp":520000,"revenues_2014":2284958065,"days_employed_2014":184,"tuition_fees_201415":8336,"enrollment":29135,"col_adjusted_base_comp":567066.5212649945,"neighbors":[39,28,2,36,0,86,55,12],"col_adjusted_neighbor_average":518853.5587992161,"neighbor_average":500510.5},{"name":"David R. Hopkins","photo":"hopkins_2932.jpg","org_name":"Wright State University","state":"Ohio","cost_of_living":0.896,"start_term":200702,"base_comp":416000,"revenues_2014":364482034,"days_employed_2014":2526,"tuition_fees_201415":8730,"enrollment":16842,"col_adjusted_base_comp":464285.7142857143,"neighbors":[40,141,44,95,130,138,133,137],"col_adjusted_neighbor_average":353436.6989466019,"neighbor_average":323610.125},{"name":"Sally K. Mason","photo":"mason_1291.jpg","org_name":"University of Iowa","state":"Iowa","cost_of_living":0.903,"start_term":200708,"base_comp":513003,"revenues_2014":1440269000,"days_employed_2014":2345,"tuition_fees_201415":8079,"enrollment":29970,"col_adjusted_base_comp":568109.634551495,"neighbors":[41,7,37,126,26,66,79,97],"col_adjusted_neighbor_average":456069.6084894814,"neighbor_average":454162.25},{"name":"Harvey Stenger","photo":"stenger_2543.jpg","org_name":"Binghamton University","state":"New York","cost_of_living":1.153,"start_term":201201,"base_comp":510000,"revenues_2014":371584084,"days_employed_2014":731,"tuition_fees_201415":8620,"enrollment":16695,"col_adjusted_base_comp":442324.3712055507,"neighbors":[42,136,22,64,88,102,110,123],"col_adjusted_neighbor_average":399384.291976224,"neighbor_average":378928.25},{"name":"Rebecca M. Blank","photo":"240444_17375.jpg","org_name":"University of Wisconsin at Madison","state":"Wisconsin","cost_of_living":0.929,"start_term":201307,"base_comp":499950,"revenues_2014":2435418415,"days_employed_2014":184,"tuition_fees_201415":10410,"enrollment":42598,"col_adjusted_base_comp":538159.3110871905,"neighbors":[43,19,51,86,0,36,17,83],"col_adjusted_neighbor_average":517261.4955716842,"neighbor_average":521978.875},{"name":"Jo Ann M. Gora","photo":"gora_1172.jpg","org_name":"Ball State University","state":"Indiana","cost_of_living":0.914,"start_term":200408,"base_comp":446338,"revenues_2014":403074003,"days_employed_2014":3440,"tuition_fees_201415":9344,"enrollment":20655,"col_adjusted_base_comp":488334.7921225383,"neighbors":[44,130,40,141,133,16,96,95],"col_adjusted_neighbor_average":411891.278280931,"neighbor_average":377979.5},{"name":"Robert J. Jones","photo":"jones_22207.jpg","org_name":"University at Albany","state":"New York","cost_of_living":1.153,"start_term":201301,"base_comp":495000,"revenues_2014":754129529,"days_employed_2014":365,"tuition_fees_201415":8302,"enrollment":17273,"col_adjusted_base_comp":429314.8308759757,"neighbors":[45,99,121,8,21,34,10,11],"col_adjusted_neighbor_average":521607.9306900955,"neighbo